### ISSUE TITLE
Discussion Thread: VIP1

### ISSUE THREAD

**Issue by strictly-scarce** [vetherasset/vips#1]
Please add your input below to VIP1. 

https://github.com/vetherasset/vips/blob/master/vip-1.md

**Comment by yellowgh0st** [comment]
@strictly-scarce 
Can we specify the deployment date please?

**Comment by strictly-scarce** [comment]
Moving VIP to status: LAST-CALL

https://github.com/vetherasset/vips/blob/master/vip-1.md
